tooltip_information_plotoptions = [
        ["At least one numeric column\nMax. Categories for factorplot: 3\nData are represented by a single point showing the confidence interval (0.95) and are connected if they belong to the same group.",
         "Pointplot\n\nInput:"],
        ["At least two numeric columns (maximum 3)\ Categories for factorplot: up to 3 supported. More categories can be added using the color option. Simply drag & drop the desired numerical or categorical column to the color button.\nAdditional categories can be added using drag & drop to the newly created color button.",
         "Scatter\n\nInput:"],
         ["At least two numeric columns\nCategories are not supported.\nTime series option uses the first column as the x-axis and all addition columns are plotted against this value. E.g. the first column should be the time while the following columns are numeric values (measurements)",
         "Time Series\n\nInput:"],
          ["At least two numeric columns\nCategories are not supported.\nColors and Size changes might be added as described for scatter plots.",
         "Scatter Matrix\n\nInput:"],
           ["At least one numeric column\nUnlimtited categories can be added.\nIf categorical columns are present each combination of categories will be used to slice data and to display the density information.",
         "Density plot\n\nInput:"],
            ["At least one numeric column\nMax. Categories for factorplot: 3\nUnlimited when Split categories disabled.\nThe error bars indicate the confidence interval (0.95).\nAdditional Options: Split Categories and split categories in different subplots.",
         "Barplot\n\nInput:"],
        ["At least one numeric column\nMax. Categories for factorplot: 3\nUnlimited when Split categories disabled.\n\nAdditional Options: Split Categories and split categories in different subplots.",
         "Boxplot\n\nInput:"],
         ["At least one numeric column\nMax. Categories for factorplot: 3\nUnlimited when Split categories disabled.\n\nAdditional Options: Split Categories and\nsplit categories in different subplots.\nViolin plot show a boxplot inside as well kernel density information",
         "Violinplot\n\nInput:"],
        ["At least one numeric column\nMax. Categories for factorplot: 3\nUnlimited when Split categories disabled.\n\nAdditional Options: Split Categories and\nsplit categories in different subplots.\nSwarmplots show the raw data points separated by jitter on x-axis.",
         "Swarmplot\n\nInput:"],
        ["Raw datapoints separated by jitter can be added to: Box-, Bar-, and Violinplots. The datapoints cannot be changed in color and size.",
         "Add swarm to plot\n\nInput:"],
         ["At least two numeric column\nCategories are not supported.",
         "Hierachical Clustering\n\nInput:"],
        ["At least two numeric columns.\nA correlation matrix calculates the Pearson correlation coefficient and uses hierachical clustering for interpretation.",
         "Correlation Matrix\n\nInput:"],
        # ["Up to one nuermic column to control size of each node.\nAt least two categorical columns to describe the edges.",
        # "Network\n\nInput:"],
           ["Opens a popup that allows you too change details of your created chart.\nNote that you can also save settings as templates and load them to get the exact same chart configuration.\nFor same coloring it is essential that the categories are sorted in the same way as in the template.",
         "Configure\n\n"]
        ]

